spring.application.name=backend-vidrieria
server.port=8080

# Conexión vía Session Pooler (IPv4 en puerto 6543)
spring.datasource.url=jdbc:postgresql://aws-0-us-west-2.pooler.supabase.com:6543/postgres?sslmode=require&prepareThreshold=0
spring.datasource.username=postgres.bcrhhexcxtiwntuilpto
spring.datasource.password=hgs5fpiFEnUwkzVw
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Ejecutar data.sql después de que Hibernate actualice el esquema
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

# JWT
jwt.secret=dmlkcmllcmlhLWJhY2tlbmQtc2VjcmV0LWtleS0yMDI2LXN1cGVyLXNlY3VyZS1rZXktMjU2Yml0cw==
jwt.expiration-ms=86400000